#!/usr/bin/env node
/**
 * Generates docs/content-gaps.md by reading the repo.
 *
 * Every gap is recorded where the work happens — a TODO(content) marker in a
 * data file, `isPlaceholder: true` in the image manifest, `isStub: true` on an
 * article — so this document is a view of the code rather than a second list
 * that has to be kept in step with it. Run `npm run docs:gaps`.
 */
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const SRC = join(ROOT, "src");

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(SRC).filter((f) => /\.(tsx?|ts)$/.test(f));

// --- TODO(content) markers ------------------------------------------------
const markers = [];
for (const file of files) {
  const rel = relative(ROOT, file);
  readFileSync(file, "utf8")
    .split("\n")
    .forEach((line, i) => {
      if (!/TODO\(content\)/.test(line)) return;
      // Skip the explanatory comments in the helper that hides them.
      if (rel.endsWith("lib/content.ts")) return;
      const label = line.match(/label: "([^"]+)"/)?.[1] ?? null;
      const field = line.match(/^\s*(\w+):/)?.[1] ?? null;
      const ask =
        line.match(/TODO\(content\):?\s*([^"']*)/)?.[1]?.trim().replace(/[,"]$/, "") || "";
      markers.push({ file: rel, line: i + 1, label, field, ask });
    });
}

const byFile = new Map();
for (const m of markers) {
  if (!byFile.has(m.file)) byFile.set(m.file, []);
  byFile.get(m.file).push(m);
}

// --- placeholder photography ---------------------------------------------
const manifest = readFileSync(join(SRC, "data/images.ts"), "utf8");
const imageKeys = [...manifest.matchAll(/^  (\w+): \{\n(?:.*?\n)*?  \},$/gm)];
const placeholders = imageKeys.filter((m) => /isPlaceholder: true/.test(m[0])).length;

// --- stub articles --------------------------------------------------------
const insights = readFileSync(join(SRC, "data/insights.ts"), "utf8");
const articles = [...insights.matchAll(/slug: "([^"]+)"/g)].map((m) => m[1]);
const stubs = [...insights.matchAll(/slug: "([^"]+)"(?:[\s\S]*?)?isStub: true/g)];
const stubCount = (insights.match(/isStub: true/g) ?? []).length;

// --- unsourced specifications ---------------------------------------------
const products = readFileSync(join(SRC, "data/products.ts"), "utf8");
const specRows = (products.match(/\{ label: "[^"]+", value: "/g) ?? []).length;
const sourced = (products.match(/source: "/g) ?? []).length;

const WHY = {
  "src/data/projects.ts":
    "Reference installations. `outcome` is the field that converts — a measurable result is worth more than the rest of the page. Anything still marked is hidden at render time, so a half-finished case study never reaches a reader.",
  "src/data/products.ts":
    "Product specifications. These appear in the visible spec table, the comparison table on /products and in `Product.additionalProperty` structured data, where a customer or a search engine may read them as a commitment. Rows carrying a marker are omitted from all three.",
  "src/data/company.ts":
    "Regional network. Four countries are listed with no way to contact any of them, which is what most undermines the 'global engineering network' claim.",
};

const sections = [...byFile.entries()]
  .sort((a, b) => b[1].length - a[1].length)
  .map(([file, rows]) => {
    const body = rows
      .map(
        (r) =>
          `| \`${r.label ?? r.field ?? "—"}\` | ${r.ask || "confirm"} | [${file}:${r.line}](${file}#L${r.line}) |`,
      )
      .join("\n");
    return `### \`${file}\` — ${rows.length} ${rows.length === 1 ? "marker" : "markers"}

${WHY[file] ?? ""}

| Field | Needed | Location |
|---|---|---|
${body}
`;
  })
  .join("\n");

const doc = `# Content gaps — IPS-PL

<!-- GENERATED by scripts/content-gaps.mjs — run \`npm run docs:gaps\`.
     Fill the gap in the data file; this document follows. -->

Everything below has **working code waiting behind it**. Supply the content and
it renders — nothing needs rebuilding.

Nothing here is guessed. Where domain knowledge was required and IPS-PL has not
published it, the field carries a \`TODO(content)\` marker rather than a
plausible figure. Markers are hidden from readers at render time
(\`src/lib/content.ts\`) and stripped from structured data, so an unanswered
question shows as an absent row, never as an invented one.

## Summary

| Gap | Count | Blocks launch? |
|---|---|---|
| \`TODO(content)\` markers | ${markers.length} | Partly — see per-file notes |
| Placeholder photographs | ${placeholders} of ${imageKeys.length} | **Yes** — see [photography-brief.md](./photography-brief.md) |
| Stub articles | ${stubCount} of ${articles.length} | No — they publish, but thinly |
| Specification rows with a stated source | ${sourced} of ${specRows} | **Yes** — every figure needs engineering sign-off |

## Checking progress

\`\`\`bash
grep -rn "TODO(content)" src/     # ${markers.length} markers
npm run check:images              # ${placeholders} placeholder images
npm run docs:gaps                 # regenerate this file
\`\`\`

## Markers by file

${sections}
## Stub articles

${stubCount} of the ${articles.length} articles are flagged \`isStub: true\`. They are
structurally complete — heading, paragraphs, and in some cases lists — but each
is a few hundred words where the subject warrants more, and none makes a claim
that is not already published elsewhere on the site.

Read time is computed from the word count, so the label cannot overstate the
article: expanding one changes its stated read time automatically.

While the flag is set, a magenta badge appears beside the article in
development. It is compiled out of production builds.

${stubs.map((m) => `- \`${m[1]}\``).join("\n")}

## Specification sign-off

${sourced === 0 ? "**No specification row currently states a source.**" : `${sourced} of ${specRows} rows state a source.`}
Every figure in \`src/data/products.ts\` was written as typical of ASTM F1545
lined equipment. They are internally consistent but **not taken from an IPS-PL
datasheet**, and the spec table says so in a note beneath it.

To sign a figure off, add a \`source\` to the row:

\`\`\`ts
{
  label: "Design pressure",
  value: "Full vacuum to 10 bar g",
  source: "IPS-PL datasheet PL-100 rev C",   // removes the indicative note
  note: "at 20 °C",                          // optional qualifier
}
\`\`\`

The note beneath the table disappears once every row on it carries a source.

## What is deliberately absent

These are not gaps to fill. They are absences that are correct until IPS-PL
supplies the underlying fact:

- **\`Organization.sameAs\`** — omitted rather than invented. Add
  \`contact.linkedin\` in \`src/data/company.ts\` and it appears in structured
  data and the footer together.
- **Named article authors** — articles are attributed to "IPS-PL Engineering".
  A named author with credentials is a stronger signal, but only with consent.
- **Client names on case studies** — withheld by agreement. A named reference
  is the strongest signal in industrial procurement, so it is worth asking.
- **Certifications beyond ISO 9001:2015** — only the one IPS-PL holds is claimed.
`;

writeFileSync(join(ROOT, "docs/content-gaps.md"), doc);
console.log(
  `✓ docs/content-gaps.md — ${markers.length} markers, ${placeholders} placeholder images, ${stubCount} stub articles`,
);
